/* eslint-disable @next/next/no-sync-scripts */
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "../styles/_.css";
import ThemeProvider from "@/providers/theme-provider";
import Header from "@/components/header";
import { storyblokInit, apiPlugin } from "@storyblok/react";

import Grid from "../components/Grid";
import Page from "../components/page";
import Teaser from "../components/Teaser";
import Feature from "../components/Feature";

const components = {
  grid: Grid,
  teaser: Teaser,
  page: Page,
  feature: Feature,
};

storyblokInit({
  accessToken: "A8FFXsxLGBOitHoSLEkoSgtt",
  apiOptions: {
    region: "eu",
  },
  use: [apiPlugin],
  components,
});
// If loading a variable font, you don't need to specify the font weight
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`dark ${inter.variable}`}
      suppressHydrationWarning={true}
    >
      <body>
        <ThemeProvider
          enableSystem={true}
          attribute="class"
          defaultTheme="system"
        >
          <div className={``}>
            <Header />
            <main className="container">{children}</main>
          </div>
        </ThemeProvider>

        {/* <script src="https://cdn.jsdelivr.net/npm/flowbite@1.5.0/dist/flowbite.min.js" ></script> */}
      </body>
    </html>
  );
}
