import { AssetType, Chamber, IndustrySector, MCapTier, PoliticalParty, TradeSizeTier, TransactionType, UsState } from "../model/types";


export const CHAMBERS: { [key in Chamber]: string } = {
  house: 'House',
  senate: 'Senate',
  joint: 'Joint',
};
export const STATE_NAMES: { [key in UsState]: string } = {
  al: 'Alabama',
  ak: 'Alaska',
  az: 'Arizona',
  ar: 'Arkansas',
  ca: 'California',
  co: 'Colorado',
  ct: 'Connecticut',
  de: 'Delaware',
  fl: 'Florida',
  ga: 'Georgia',
  hi: 'Hawaii',
  id: 'Idaho',
  il: 'Illinois',
  in: 'Indiana',
  ia: 'Iowa',
  ks: 'Kansas',
  ky: 'Kentucky',
  la: 'Louisiana',
  me: 'Maine',
  md: 'Maryland',
  ma: 'Massachusetts',
  mi: 'Michigan',
  mn: 'Minnesota',
  ms: 'Mississippi',
  mo: 'Missouri',
  mt: 'Montana',
  ne: 'Nebraska',
  nv: 'Nevada',
  nh: 'New Hampshire',
  nj: 'New Jersey',
  nm: 'New Mexico',
  ny: 'New York',
  nc: 'North Carolina',
  nd: 'North Dakota',
  oh: 'Ohio',
  ok: 'Oklahoma',
  or: 'Oregon',
  pa: 'Pennsylvania',
  ri: 'Rhode Island',
  sc: 'South Carolina',
  sd: 'South Dakota',
  tn: 'Tennessee',
  tx: 'Texas',
  ut: 'Utah',
  vt: 'Vermont',
  va: 'Virginia',
  // dc: 'Washington, D.C.',
  wa: 'Washington',
  wv: 'West Virginia',
  wi: 'Wisconsin',
  wy: 'Wyoming',
};
export const TRANSACTION_TYPE: { [key in TransactionType]:string } = {
    buy: 'Buy',
    sell: "Sell",
    exchange: "Exchange",
    receive:"Receive"
} 
export const POLITICAL_PARTY: { [key in PoliticalParty]:string } = {
    democrat: 'Democrats',
    republican: "Republicans",
    other: "Other",
   
}
export const COMMITTEE: { [key: string]: string } = {
  hsag: 'Agriculture',
  hsap: 'Appropriations',
  hsas: 'Armed Services',
  hsbu: 'Budget',
  hscn: 'Climate Crisis',
  hsvc: 'Coronavirus Pandemic',
  hsed: 'Education & Labor',
  hsif: 'Energy & Commerce',
  hsso: 'Ethics',
  hsba: 'Financial Services',
  hsfa: 'Foreign Affairs',
  hshm: 'Homeland Security',
  hsha: 'House Administration',
  hlig: 'Intelligence',
  hsig: 'Intelligence (Previous)', // ID has changed
  hsju: 'Judiciary',
  hsmh: 'Modernization of Congress',
  hsii: 'Natural Resources',
  hsgo: 'Oversight and Reform',
  hsru: 'Rules',
  hssy: 'Science, Space and Technology',
  hssm: 'Small business',
  hszs: 'Strategic Competition between US and CCP',
  hspw: 'Transportation & Infrastructure',
  hsvr: 'Veteran’s Affairs',
  hswm: 'Ways & Means',
  hsfd: 'Weaponization of the Federal Government',
  scnc: 'International Narcotics Control',
  slet: 'Ethics',
  slia: 'Indian Affairs',
  slin: 'Intelligence',
  spag: 'Aging',
  ssaf: 'Agriculture, Nutrition & Forestry',
  ssap: 'Appropriations',
  ssas: 'Armed Services',
  ssbk: 'Banking, Housing & Urban Affairs',
  ssbu: 'Budget',
  sscm: 'Commerce, Science & Transportation',
  sseg: 'Energy & Natural Resources',
  ssev: 'Environment & Public Works',
  ssfi: 'Finance',
  ssfr: 'Foreign Relations',
  ssga: 'Homeland Security & Gov. Affairs',
  sshr: 'Health, Education, Labor & Pensions',
  ssju: 'Judiciary',
  ssra: 'Rules and Administration',
  sssb: 'Small Business & Entrepreneurship',
  ssva: 'Veteran’s Affairs',
};
export const INDUSTRY_SECTORS: { [key in IndustrySector]: string } = {
  'communication-services': 'Communication Services',
  'consumer-discretionary': 'Consumer Discretionary',
  'consumer-staples': 'Consumer Staples',
  'energy': 'Energy',
  'financial': 'Financial',
  'health-care': 'Healthcare',
  'industrials': 'Industrials',
  'information-technology': 'Information Technology',
  'materials': 'Materials',
  'real-estate': 'Real Estate',
  'utilities': 'Utilities',
  'other': 'Other',
};
export const COUNTRIES: { [key in string]: string } = {
  af: 'Afghanistan',
  ax: 'Åland Islands',
  al: 'Albania',
  dz: 'Algeria',
  as: 'American Samoa',
  ad: 'Andorra',
  ao: 'Angola',
  ai: 'Anguilla',
  aq: 'Antarctica',
  ag: 'Antigua & Barbuda',
  ar: 'Argentina',
  am: 'Armenia',
  aw: 'Aruba',
  ac: 'Ascension Island' /*added */,
  au: 'Australia',
  at: 'Austria',
  az: 'Azerbaijan',
  bs: 'Bahamas',
  bh: 'Bahrain',
  bd: 'Bangladesh',
  bb: 'Barbados',
  by: 'Belarus',
  be: 'Belgium',
  bz: 'Belize',
  bj: 'Benin',
  bm: 'Bermuda',
  bt: 'Bhutan',
  bo: 'Bolivia',
  ba: 'Bosnia & Herzegovina',
  bw: 'Botswana',
  bv: 'Bouvet Island',
  br: 'Brazil',
  io: 'British Indian Ocean Territory',
  vg: 'British Virgin Islands',
  bn: 'Brunei',
  bg: 'Bulgaria',
  bf: 'Burkina Faso',
  bi: 'Burundi',
  kh: 'Cambodia',
  cm: 'Cameroon',
  ca: 'Canada',
  ic: 'Canary Islands' /*added */,
  cv: 'Cape Verde',
  bq: 'Caribbean Netherlands',
  ky: 'Cayman Islands',
  cf: 'Central African Republic',
  ea: 'Ceuta & Melilla' /*added */,
  td: 'Chad',
  cl: 'Chile',
  cn: 'China',
  cx: 'Christmas Island',
  cc: 'Cocos (Keeling) Islands',
  co: 'Colombia',
  km: 'Comoros',
  cg: 'Congo - Brazzaville',
  cd: 'Congo - Kinshasa',
  ck: 'Cook Islands',
  cr: 'Costa Rica',
  ci: 'Côte d’Ivoire',
  hr: 'Croatia',
  cu: 'Cuba',
  cw: 'Curaçao',
  cy: 'Cyprus',
  cz: 'Czechia',
  dk: 'Denmark',
  dg: 'Diego Garcia' /*added */,
  dj: 'Djibouti',
  dm: 'Dominica',
  do: 'Dominican Republic',
  ec: 'Ecuador',
  eg: 'Egypt',
  sv: 'El Salvador',
  gq: 'Equatorial Guinea',
  er: 'Eritrea',
  ee: 'Estonia',
  sz: 'Eswatini',
  et: 'Ethiopia',
  fk: 'Falkland Islands',
  fo: 'Faroe Islands',
  fj: 'Fiji',
  fi: 'Finland',
  fr: 'France',
  gf: 'French Guiana',
  pf: 'French Polynesia',
  tf: 'French Southern Territories',
  ga: 'Gabon',
  gm: 'Gambia',
  ge: 'Georgia',
  de: 'Germany',
  gh: 'Ghana',
  gi: 'Gibraltar',
  gr: 'Greece',
  gl: 'Greenland',
  gd: 'Grenada',
  gp: 'Guadeloupe',
  gu: 'Guam',
  gt: 'Guatemala',
  gg: 'Guernsey',
  gn: 'Guinea',
  gw: 'Guinea-Bissau',
  gy: 'Guyana',
  ht: 'Haiti',
  hm: 'Heard & McDonald Islands',
  hn: 'Honduras',
  hk: 'Hong Kong SAR China',
  hu: 'Hungary',
  is: 'Iceland',
  in: 'India',
  id: 'Indonesia',
  ir: 'Iran',
  iq: 'Iraq',
  ie: 'Ireland',
  im: 'Isle of Man',
  il: 'Israel',
  it: 'Italy',
  jm: 'Jamaica',
  jp: 'Japan',
  je: 'Jersey',
  jo: 'Jordan',
  kz: 'Kazakhstan',
  ke: 'Kenya',
  ki: 'Kiribati',
  xk: 'Kosovo' /* added */,
  kw: 'Kuwait',
  kg: 'Kyrgyzstan',
  la: 'Laos',
  lv: 'Latvia',
  lb: 'Lebanon',
  ls: 'Lesotho',
  lr: 'Liberia',
  ly: 'Libya',
  li: 'Liechtenstein',
  lt: 'Lithuania',
  lu: 'Luxembourg',
  mo: 'Macao SAR China',
  mg: 'Madagascar',
  mw: 'Malawi',
  my: 'Malaysia',
  mv: 'Maldives',
  ml: 'Mali',
  mt: 'Malta',
  mh: 'Marshall Islands',
  mq: 'Martinique',
  mr: 'Mauritania',
  mu: 'Mauritius',
  yt: 'Mayotte',
  mx: 'Mexico',
  fm: 'Micronesia',
  md: 'Moldova',
  mc: 'Monaco',
  mn: 'Mongolia',
  me: 'Montenegro',
  ms: 'Montserrat',
  ma: 'Morocco',
  mz: 'Mozambique',
  mm: 'Myanmar (Burma)',
  na: 'Namibia',
  nr: 'Nauru',
  np: 'Nepal',
  nl: 'Netherlands',
  nc: 'New Caledonia',
  nz: 'New Zealand',
  ni: 'Nicaragua',
  ne: 'Niger',
  ng: 'Nigeria',
  nu: 'Niue',
  nf: 'Norfolk Island',
  kp: 'North Korea',
  mk: 'North Macedonia',
  mp: 'Northern Mariana Islands',
  no: 'Norway',
  om: 'Oman',
  pk: 'Pakistan',
  pw: 'Palau',
  ps: 'Palestinian Territories',
  pa: 'Panama',
  pg: 'Papua New Guinea',
  py: 'Paraguay',
  pe: 'Peru',
  ph: 'Philippines',
  pn: 'Pitcairn Islands',
  pl: 'Poland',
  pt: 'Portugal',
  pr: 'Puerto Rico',
  qa: 'Qatar',
  re: 'Réunion',
  ro: 'Romania',
  ru: 'Russia',
  rw: 'Rwanda',
  ws: 'Samoa',
  sm: 'San Marino',
  st: 'São Tomé & Príncipe',
  sa: 'Saudi Arabia',
  sn: 'Senegal',
  rs: 'Serbia',
  sc: 'Seychelles',
  sl: 'Sierra Leone',
  sg: 'Singapore',
  sx: 'Sint Maarten',
  sk: 'Slovakia',
  si: 'Slovenia',
  sb: 'Solomon Islands',
  so: 'Somalia',
  za: 'South Africa',
  gs: 'South Georgia & South Sandwich Islands',
  kr: 'South Korea',
  ss: 'South Sudan',
  es: 'Spain',
  lk: 'Sri Lanka',
  bl: 'St. Barthélemy',
  sh: 'St. Helena',
  kn: 'St. Kitts & Nevis',
  lc: 'St. Lucia',
  mf: 'St. Martin',
  pm: 'St. Pierre & Miquelon',
  vc: 'St. Vincent & Grenadines',
  sd: 'Sudan',
  sr: 'Suriname',
  sj: 'Svalbard & Jan Mayen',
  se: 'Sweden',
  ch: 'Switzerland',
  sy: 'Syria',
  tw: 'Taiwan',
  tj: 'Tajikistan',
  tz: 'Tanzania',
  th: 'Thailand',
  tl: 'Timor-Leste',
  tg: 'Togo',
  tk: 'Tokelau',
  to: 'Tonga',
  tt: 'Trinidad & Tobago',
  ta: 'Tristan da Cunha' /* added */,
  tn: 'Tunisia',
  tr: 'Turkey',
  tm: 'Turkmenistan',
  tc: 'Turks & Caicos Islands',
  tv: 'Tuvalu',
  um: 'U.S. Outlying Islands',
  vi: 'U.S. Virgin Islands',
  ug: 'Uganda',
  ua: 'Ukraine',
  ae: 'United Arab Emirates',
  gb: 'United Kingdom',
  us: 'United States',
  uy: 'Uruguay',
  uz: 'Uzbekistan',
  vu: 'Vanuatu',
  va: 'Vatican City',
  ve: 'Venezuela',
  vn: 'Vietnam',
  wf: 'Wallis & Futuna',
  eh: 'Western Sahara',
  ye: 'Yemen',
  zm: 'Zambia',
  zw: 'Zimbabwe',
};
export const TRADE_SIZE_TIERS: TradeSizeTier[] = [
  { id: 1,  min: 0,         max: 1000,      display: '< 1K'        },
  { id: 2,  min: 1001,      max: 15000,     display: '1K–15K'    },
  { id: 3,  min: 15001,     max: 50000,     display: '15K–50K'   },
  { id: 4,  min: 50001,     max: 100000,    display: '50K–100K'  },
  { id: 5,  min: 100001,    max: 250000,    display: '100K–250K' },
  { id: 6,  min: 250001,    max: 500000,    display: '250K–500K' },
  { id: 7,  min: 500001,    max: 1000000,   display: '500K–1M'   },
  { id: 8,  min: 1000001,   max: 5000000,   display: '1M–5M'     },
  { id: 9,  min: 5000001,   max: 25000000,  display: '5M–25M'    },
  { id: 10, min: 25000001,  max: 50000000,  display: '25M–50M'   },
];
export const GENDER: { [key: string]: string } = {
  male: 'Male',
  female: 'Female',
};
export const MARKET_CAP_TIERS: MCapTier[] = [
  { id: 1, min: 2e11 + 1, max: Infinity, display: 'Mega (> 200B)'     },
  { id: 2, min: 1e10 + 1, max: 2e11,     display: 'Large (10B - 200B)' },
  { id: 3, min: 2e9 + 1,  max: 1e10,     display: 'Mid (2B - 10B)'     },
  { id: 4, min: 3e8 + 1,  max: 2e9,      display: 'Small (300M - 2B)'  },
  { id: 5, min: 5e7 + 1,  max: 3e8,      display: 'Micro (50M - 300M)' },
  { id: 6, min: 0,        max: 5e7,      display: 'Nano (< 50M)'      },
];
export const ASSET_TYPES: { [key in AssetType]: string } = {
  'abs':                        'ABS',
  'corporate-bond':             'Corporate Bond',
  'crypto':                     'Crypto',
  'etf':                        'ETF',
  'etn':                        'ETN',
  'futures':                    'Futures',
  'municipal-security':         'Municipal Security',
  'hedge-pvt-eq-funds-non-eif': 'Hedge/Pvt Eq Funds (non-EIF)',
  'mutual-fund':                'Mutual Fund',
  'non-public-stock':           'Non-Public Stock',
  'indices':                    'indices',
  'other-investment-fund':      'Other Investment Fund',
  'other-securities':           'Other Securities',
  'ownership-interest':         'Ownership Interest',
  'preferred-shares':           'Preferred Shares',
  'private-equity-fund':        'Private Equity Fund',
  'reit':                       'REIT',
  'stock':                      'Stock',
  'stock-appreciation-right':   'Stock Appreciation Right',
  'stock-options':              'Stock Options',
  'variable-annuity':           'Variable Annuity',
  'venture-capital':            'Venture Capital',
};
export const TRANSACTION_LABELS: { [key: string]: string } = {
  // covid: 'Covid',
  crypto: 'Crypto',
  // diamondhands: 'Diamond hands trader',
  faang: 'FAANG stock',
  memestock: 'Meme stock',
  // metaverse: 'Metaverse',
  spac: 'SPAC',
  // whale: 'Whale trader',
};